### ISSUE TITLE
not able to auth/login

### ISSUE THREAD

**Issue by fluidvoice** [talhasch/lander#2]
I created my page some weeks ago and it was working fine for many days. Now I've not been able to login for over a week no matter the browser I use.  All other Blockstack apps are working fine.
error I get >> https://imgur.com/t0DsQKT.png
![t0DsQKT](https://user-images.githubusercontent.com/373038/69648575-5c46f580-104a-11ea-83ae-e57e0a432ed1.png)

**Comment by fluidvoice** [comment]
abandoned app. wtf?

**Comment by talhasch** [comment]
@fluidvoice  No, we are still here :) This is a bug we are going to fix in a couple days. Thanks for feedback.

**Comment by fluidvoice** [comment]
> @fluidvoice No, we are still here :) This is a bug we are going to fix in a couple days. Thanks for feedback.

That's a long couple days :-)  Just pinging you. I'm still waiting, as are others.
This used to work, what broke it?

**Comment by talhasch** [comment]
@fluidvoice we've fixed this problem. basically it was about a design problem on blockstack's radiks code. we forked radiks code and patched it on another repo and applied to lander.

**Comment by fluidvoice** [comment]
> @fluidvoice we've fixed this problem. basically it was about a design problem on blockstack's radiks code. we forked radiks code and patched it on another repo and applied to lander.

Now I'm getting a 504 error when I try to open my page: https://landr.me/fluidvoice

**Comment by talhasch** [comment]
all fixed
